version : "3"
services:
  chirpi:
    build:
      context: .
      dockerfile: dockerfiles/Web.Dockerfile
    container_name: chirpi
    depends_on:
      - chirpi-pg
    volumes:
      - .:/var/www/html
    restart: always
    ports:
      - "2362:80"
    environment:
      APP_NAME: "Chirpi"
    networks:
      chirpi-network:
        ipv4_address: 23.62.1.1
    extra_hosts:
      - host.docker.internal:host-gateway

  chirpi-pg:
    image: postgres:15
    container_name: chirpi-pg
    volumes:
      - chirpi-pg-disk:/var/lib/postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: testing
    networks:
      chirpi-network:
        ipv4_address: 23.62.1.2

  chirpi-q:
    build:
      context: .
      dockerfile: dockerfiles/QueueListener.Dockerfile
    container_name: chirpi-q
    depends_on:
      - chirpi
    volumes:
      - .:/var/www/html
    restart: unless-stopped
    networks:
      chirpi-network:
        ipv4_address: 23.62.1.3

  chirpi-mailpit:
    image: 'axllent/mailpit:latest'
    container_name: chirpi-mailpit
    restart: always
    networks:
      chirpi-network:
        ipv4_address: 23.62.1.4

  chirpi-0x:
    build:
      context: .
      dockerfile: dockerfiles/SansXdebug.Dockerfile
    container_name: chirpi-0x
    depends_on:
      - chirpi
    volumes:
      - .:/var/www/html
    restart: always
    networks:
      chirpi-network:
        ipv4_address: 23.62.1.5

  chirpi-fe:
    build:
      context: .
      dockerfile: dockerfiles/Fe.Dockerfile
    container_name: chirpi-fe
    ports:
      - "2363:5173"
    depends_on:
      - chirpi
    volumes:
      - .:/var/www/html
    restart: unless-stopped
    networks:
      chirpi-network:
        ipv4_address: 23.62.1.6

# On-disk storage of DB data, when containers are stopped
volumes:
  chirpi-pg-disk: {}

# Local network for services running using this docker-compose config
networks:
  chirpi-network:
    ipam:
      driver: default
      config:
        - subnet: 23.62.0.0/16
