version : "3"
services:
  chirhi:
    build:
      context: .
      dockerfile: dockerfiles/Web.Dockerfile
    container_name: chirhi
    depends_on:
      - chirhi-pg
    volumes:
      - .:/var/www/html
    restart: always
    ports:
      - "2362:80"
    environment:
      APP_NAME: "Chirhi"
    networks:
      chirhi-network:
        ipv4_address: 23.62.1.1
    extra_hosts:
      - host.docker.internal:host-gateway

  chirhi-pg:
    image: postgres:15
    container_name: chirhi-pg
    volumes:
      - chirhi-pg-disk:/var/lib/postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: testing
    networks:
      chirhi-network:
        ipv4_address: 23.62.1.2

  chirhi-q:
    build:
      context: .
      dockerfile: dockerfiles/QueueListener.Dockerfile
    container_name: chirhi-q
    depends_on:
      - chirhi
    volumes:
      - .:/var/www/html
    restart: unless-stopped
    networks:
      chirhi-network:
        ipv4_address: 23.62.1.3

  chirhi-mailpit:
    image: 'axllent/mailpit:latest'
    container_name: chirhi-mailpit
    restart: always
    networks:
      chirhi-network:
        ipv4_address: 23.62.1.4

  chirhi-0x:
    build:
      context: .
      dockerfile: dockerfiles/SansXdebug.Dockerfile
    container_name: chirhi-0x
    depends_on:
      - chirhi
    volumes:
      - .:/var/www/html
    restart: always
    networks:
      chirhi-network:
        ipv4_address: 23.62.1.5

  chirhi-fe:
    build:
      context: .
      dockerfile: dockerfiles/Fe.Dockerfile
    container_name: chirhi-fe
    ports:
      - "2363:5173"
    depends_on:
      - chirhi
    volumes:
      - .:/var/www/html
    restart: unless-stopped
    networks:
      chirhi-network:
        ipv4_address: 23.62.1.6

# On-disk storage of DB data, when containers are stopped
volumes:
  chirhi-pg-disk: {}

# Local network for services running using this docker-compose config
networks:
  chirhi-network:
    ipam:
      driver: default
      config:
        - subnet: 23.62.0.0/16
