name: CoIn

on:
  push:
    branches:
      - main
      - '*.x'
  pull_request:
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: read

jobs:
  CoIn:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Docker Compose
        run: docker-compose up -d

      - name: Composer install [manual]
        run: docker-compose exec -T chirhi composer install

      - name: CI
        run: docker-compose exec -T chirhi composer run ci
