name: CoIn

on:
  push:
    branches:
      - main
      - '*.x'
  pull_request:
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: read

jobs:
  CoIn:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Docker Compose
        run: docker-compose -f ci-docker-compose.yml up -d

      - name: CI
        run: docker-compose -f ci-docker-compose.yml exec -T ci-chirpi composer run ci
